out = open("topics.301-450.trec", "w")
f = open("topics.301-350.trec6", "r")
out.write(f.read())
out.write("\n \n")
f.close()
f = open("topics.351-400.trec7", "r")
out.write(f.read())
out.write("\n \n")
f.close()
f = open("topics.401-450.trec8", "r")
out.write(f.read())
f.close()
out.close()